### ISSUE TITLE
Implementação de React PropTypes

### ISSUE THREAD

**Issue by gabrielduete** [Pews-DEV/book-writer-frontend#15]
# Salve galera! Beleza?

Estava pensando na escalabilidade do projeto e pensei em implementar o [React PropTypes](https://pt-br.reactjs.org/docs/typechecking-with-proptypes.html) no projeto. O mesmo ia garantir segurança e diminuir as chances de bugs por conta de tipagem de dados. O PropTypes ia validar se os dados passados por props seria de fato o tipo de dado esperado, se for um tipo errado, ele deve retornar erro no console. assim a gente garante que os dados sejam passados de maneira correta e evitar problemas futuros. 

O Possíveis erros de PropTypes iam ser apenas exibidos em ambientes de DEV(podemos configurar isso via ESLINT se não me engano), então não seria problema subir pra PROD, já que nenhuma mensagem de erro seria exibida no console em produção caso algum dado esteja inválido.

### Segue um exemplo de uso de PropTypes:

![image](https://user-images.githubusercontent.com/59345698/163767297-5d3c3d39-0d1d-4f15-ad04-cfe71dae418a.png)
Nesse exemplo, o PropTypes obriga a passarmos uma `string` pra `prop titulo`, assim garantindo que caso outro tipo de dado seja passado, vamos ser notificados pelo console.

Não é uma Feature grande, mas iria deixar nosso código mais confiável e mais escalável, longe de bugs ou problemas indesejados. O que vocês acham?

**Comment by oopaze** [comment]
Acho muito importante a gente aplicar os `PropTypes`. Esse módulo pode nos ajudar tanto na validação das nossas props no client side, quanto na documentação do que nossos componentes realmente esperam como props. 

Inclusive @gabrielduete, é uma boa a gente tem ver como organizar esses `PropTypes`. Talvez seja uma boa na pasta do componente a gente ter um arquivo `Component.PropTypes.js` ou `index.proptypes.js`.

O que acha a gente implementar isso @Pews-DEV?

**Comment by oopaze** [comment]
@gabrielduete, pq tu tá me gritando?

**Comment by Pews-DEV** [comment]
Opa, cara pelo que eu entendi sobre o prototypes, é tipo o que o typescript tem por padrão, acho interessante essa ideia e apoio a implementação, já havia conversado com Zé sobre erros de tipagem que o javascript tem, então essa ferramenta seria uma boa solução!

**Comment by oopaze** [comment]
Feature adicionada nesse PR: https://github.com/Pews-DEV/book-writer-frontend/pull/17
