### ISSUE TITLE
Padronização do HTML

### ISSUE THREAD

**Issue by gabrielduete** [Pews-DEV/book-writer-frontend#18]
Question: Seria interessante criar um style pra div nos styles? Mesmo que vazio, para seguir o padrão, já que os os outros elementos estão no .styles.

`export const WrapperImage = styled.div`` `

_Originally posted by @gabrielduete in https://github.com/Pews-DEV/book-writer-frontend/pull/5#discussion_r838769153_

**Comment by oopaze** [comment]
Eu entendi o porque mas acho que é melhor usar a html tag mesmo.

Acredito que seja interessante a utilização do styled-components somente quando o elemento necessitar de estilo, pois desse modo a gente escreve menos código (tamanho do arquivo não escala desnecessariamente) facilitando a legibilidade dos arquivos styles.ts e também evita as lógicas de estilização do styled components em componentes que não necessitam de estilização.
